Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/lunar64"
  config.vm.hostname = "trabalho-extra"
  config.vm.network "public_network"
  config.vm.synced_folder "./guilherme/", "/home/vagrant/guilherme", type: "virtualbox"

  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y docker docker.io docker-compose
     sudo usermod -aG docker vagrant
     apt-get upgrade -y
     sudo reboot
  SHELL
end
